import "AudioFrame.idl";

namespace Interop
{
    [default_interface]
    runtimeclass AudioCapture
    {
        AudioCapture();
        
        Windows.Media.MediaProperties.AudioEncodingProperties AudioEncodingProperties { get; };
        Windows.Foundation.IAsyncAction InitializeAsync();
        Windows.Foundation.IAsyncAction StartCaptureAsync();
        Windows.Foundation.IAsyncAction StopCaptureAsync();
        UInt8[] GetNextAudioBytes(UInt32 size);
    }
}
